### ISSUE TITLE
Comic Strips Navigation

### ISSUE THREAD

**Issue by gardnersm** [spoyser/spoyser-repo#14]
When viewing a comic strip, are there keyboard control that allow to go to next or previous image within same comic? I've been looking around for any info on the plugin and how to navigate but have found nothing so far.

Thanks!

**Comment by spoyser** [comment]
You should be able to use the right and left arrows, but it looks like it
isn't working at the moment, which suggest the website may have changed
slightly.

I will take a look and get it fixed.


Best Regards,

Sean

**Comment by gardnersm** [comment]
Awesome! Thanks so much for the great addon.
