### ISSUE TITLE
watchcartoononline version 1.0.16 / 1.0.17

### ISSUE THREAD

**Issue by cloutian** [spoyser/spoyser-repo#19]
New features added but unable to see any content after selecting title. List will be empty. Verified using platforms: Raspberry Pi2 (openelec - isengard) || Windows 10 (isengard). 
![1](https://cloud.githubusercontent.com/assets/12385610/10271214/85da638c-6ad6-11e5-9ad5-4492cc457a12.jpg)
![2](https://cloud.githubusercontent.com/assets/12385610/10271215/85dab6f2-6ad6-11e5-9966-06b50ea3092e.jpg)
![3](https://cloud.githubusercontent.com/assets/12385610/10271216/85db1296-6ad6-11e5-9905-712390837d2a.jpg)
![4](https://cloud.githubusercontent.com/assets/12385610/10271213/85d94a42-6ad6-11e5-92ff-b00453caefee.jpg)

**Comment by TheLivebox** [comment]
Resolved in 1.0.18
