### ISSUE TITLE
What is the protocol path for getting directory listing of particular label?

### ISSUE THREAD

**Issue by shivamkalra** [spoyser/spoyser-repo#26]
I'm creating a super favourite's widget for my theme. I'm trying to figure out the protocol path for getting the favourite items for a particular label within super favourite addon.

For example, I've created a label `News` and added bunch of news channels to that label or folder of super favourite. Now I can browse those news channels when I open the super favourite addon and go to `News` folder. But what is the protocol url for accessing that particular folder (i'm sure somwhere in code the menu link must have been created, but not sure what it looks like)? I've tried:

`plugin://plugin.program.super.favourites/label=News&mode=650`

but this just gives listing of home directory of the plugin instead of `News`. Can you provide some information on how this protocol url is constructed for plugin menus? Does it need more parameters?

**Comment by spoyser** [comment]
From memory you can just do

`plugin://plugin.program.super.favourites?folder=News`

Sub-folders: 

`plugin://plugin.program.super.favourites?folder=News/Folder1`

**Comment by shivamkalra** [comment]
It works! Thank you. 

Is there any way to hide `Create New Folder Here`? I believe I can create a `mode` that will only list the items in the directory without `Create New Folder`.

**Comment by TheLivebox** [comment]
There is a setting under Display called "Show new Super Folder" item - disable that
You can hide just about all the items via the settings.

**Comment by spoyser** [comment]
There is a setting under Display called "Show new Super Folder" item - disable that
You can hide just about all the items via the settings.

**Comment by shivamkalra** [comment]
Thanks a lot.
