### ISSUE TITLE
Multiple words [%SF%]

### ISSUE THREAD

**Issue by corrpel** [spoyser/spoyser-repo#27]
When used this way, it is working only if one word is present. If multiple words are present, it is not working.
I am trying to use the isearch function in an addon.

edit:
I found the issue. This addon shout use "+" instead of "space"
For example if a listed item is "two words", it should isearch for "two+words" instead of "two words".
Any ideea how i can fix it using superfavorites?
Thank you.

**Comment by spoyser** [comment]
Use [%SF+%] as the placeholder rather than [%SF%] (like the Google Image Search item)

Hope that helps.
