### ISSUE TITLE
just now january 2018 watchcartoononline cannot play video

### ISSUE THREAD

**Issue by daniel-ntl** [spoyser/spoyser-repo#57]
hi, i'm new here, but i have problem with this watchcartoononline addon, it unable to play video, the addon version is 1.1.7 by dandy and the repo is kodil repo, it cannot play video just january 2018, last december 2017 the addon just fine, please help, thx again

**Comment by kodibear** [comment]
Check out my fork of the plugin, which works with the changed version of WCO: https://github.com/kodibear/plugin.video.watchcartoononline

**Comment by daniel-ntl** [comment]
thx man much appreciated, good job

________________________________

**Comment by daniel-ntl** [comment]
to all here is the working WCO, works in kodi frodo and jarvis, thx to kodibear,
https://github.com/kodibear/plugin.video.watchcartoononline,
case closed
